DAS/Models/Mapa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DAS.Models
{
    public class Mapa
    {
        int id;
        String place;
    }
}

DAS/Models/ZaNas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DAS.Models
{
    public class ZaNas
    {
        int id;
    }
}

DAS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DAS/Controllers/MapaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAS.Controllers
{
    public class MapaController : Controller
    {
        // GET: Mapa
        public ActionResult Index()
        {
            return View("View2");
        }

        // GET: Mapa/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mapa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mapa/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mapa/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Mapa/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mapa/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mapa/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DAS/Controllers/ZaNasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAS.Controllers
{
    public class ZaNasController : Controller
    {
        // GET: ZaNas
        public ActionResult Index()
        {
            return View("View1");
        }

        // GET: ZaNas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ZaNas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ZaNas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ZaNas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ZaNas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ZaNas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ZaNas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DAS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DAS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DAS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DAS/Views/Mapa/View2.cshtml
@model DAS.Models.Mapa

@{
    ViewBag.Title = "View";
}

    <div id="levo">
        <div id="pregled">
            <p>
                На оваа страна може да имате преглед врз целата мапа на Скопје
                на која се прикажани по неколку бизниси од соодветната категорија
            </p>
        </div>
        <div id="mapa">
            <div class="mapouter">
                <div class="gmap_canvas">
                    <iframe width="700px" height="450px" id="gmap_canvas"
                            src="https://maps.google.com/maps?q=skopje&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            frameborder="0"
                            scrolling="no"
                            marginheight="0"
                            marginwidth="0">
                    </iframe><a href="https://embedgooglemap.net/134/">torrentz2</a>
                </div>
                <style>
                    .mapouter {
                        position: relative;
                        text-align: right;
                        height: 450px;
                        width: 700px;
                    }

                    .gmap_canvas {
                        overflow: hidden;
                        background: none !important;
                        height: 450px;
                        width: 700px;
                    }
                </style>
            </div>
        </div>
    </div>

    <div id="desno">
        <div id="lokali">
            <ul id="selectable">
                <li>Хотели</li>
                <li>Кафулиња</li>
                <li>Пекари</li>
                <li>Фризерски салони</li>
                <li>Продавници за облека</li>
            </ul>
            <div id="skopje">
                <img src="Images/skopje.png" width="300px" height="200px">
            </div>
        </div>
    </div>

DAS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Welcome!</title>
     @Styles.Render("~/Content/css") 
     @Scripts.Render("~/bundles/modernizr") 
    <link href="~/izgled.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav ">
                    <!-- Controller, Akcija, parametar od akcijata  -->
                    <li>@Html.ActionLink("За нас", "ZaNas", "View")</li>
                    <li>@Html.ActionLink("Мапа", "Mapa", "View")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DAS/Views/View.cshtml
@model DAS.Models.ZaNas

@{
    ViewBag.Title = "View";
}

DAS/Views/ZaNas/View1.cshtml
@model DAS.Models.ZaNas

@{
    ViewBag.Title = "View";

}

    <body>

        <div>
            <div>
                <h4>Добредојдовте на нашиот сајт</h4>
            </div>
            <div>
                <p>
                    Овој сајт претставува едноставно пребарување на локации за хотели, локали, барови,
                    пекари, продавници за облека, како и фризерски салони кои се наоѓаат на територијата на
                    град Скопје
                </p>
            </div>
            <div id="desno">
                <div id="lokali">
                    <ul id="selectable">
                        <li>Хотели</li>
                        <li>Кафулиња</li>
                        <li>Пекари</li>
                        <li>Фризерски салони</li>
                        <li>Продавници за облека</li>
                    </ul>
                    <div id="skopje">
                        <img src="images/skopje.png" width="300px" height="200px">
                    </div>
                </div>
            </div>
        </div>

    </body>